[package]
name = "mbpg-light"
version = "0.1.0"
edition = "2024"

[dependencies]
sqlx = { version = "0.8", features = ["postgres", "runtime-tokio-native-tls", "macros"] }
tokio = { version = "1", features = ["full"] }
tokio-postgres = "0.7.13"
tokio-util = "0.7"
futures-util = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"
config = "0.15.15"
reqwest = { version = "0.12.23", features = ["stream"] }
tempfile = "3"
async-compression = { version = "0.4.30", features = ["tokio", "bzip2"] }
bzip2 = "0.4"
tar = "0.4"
bytes = "1"
octocrab = "0.45.0"
indicatif = "0.17.0"
