from_latest_tag = false
ignore_merge_commits = true
ignore_fixup_commits = true
branch_whitelist = ["main"]
skip_ci = "[skip ci]"
skip_untracked = false
pre_bump_hooks = [
    "cargo fmt --all",
    "cargo clippy -- -D warnings",
    "cargo test",
    "cargo build --release",
    "cargo set-version {{version}}",
]
post_bump_hooks = [
    "git push",
    "git push origin {{version}}",
    "cargo package",
    "cargo publish"
]

[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
repository = "musicbrainz-light"
owner = "oknozor"
authors = [
    { signature = "Paul Delafosse", username = "oknozor" },
]
